# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: check-yaml
        args: [--unsafe]
    -   id: check-added-large-files
-   repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
    -   id: dockerfilelint
-   repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v3.0.1
    hooks:
    -   id: docker-compose-check
-   repo: local
    hooks:
    -   id: php-cs-fixer
        name: Check php with php-cs-fixer
        entry: jakzal/phpqa:php8.3-debian php-cs-fixer fix -v --config=.php-cs-fixer.dist.php --using-cache=no --allow-risky=yes --diff
        language: docker_image
        types: [php]
-   repo: local
    hooks:
    -   id: phpstan
        name: Check php with phpstan
        entry: docker exec etl-workflow ./vendor/bin/phpstan analyse --memory-limit=1G
        language: system
        types: [php]
        pass_filenames: false
-   repo: local
    hooks:
    -   id: rector
        name: Check php with rector
        entry: jakzal/phpqa:php8.3-debian rector process
        language: docker_image
        types: [php]
-   repo: local
    hooks:
    -   id: phpmd
        name: Check php with phpmd
        entry: jakzal/phpqa:php8.3-debian bash -c 'if [[ ! $# -eq 0 ]] ; then array="${@}"; phpmd --cache --cache-file=/tmp/.phpmd.result-cache.php ${array// /,} text phpmd-rules.xml; fi'
        language: docker_image
        types: [php]
