services:
    php:
        container_name: etl-workflow
        build: ./config/docker
        ports:
          - 9040:9040
        volumes:
            - ./:/var/www/
            - ./config/docker/etl-workflow.conf:/usr/local/etc/php-fpm.d/etl-workflow.conf
        working_dir: /var/www
